#!/usr/bin/env bun

/**
 * Health check endpoint for load balancers
 * Generated by create-karetech-stack
 */

interface HealthStatus {
  status: 'healthy' | 'unhealthy';
  timestamp: string;
  uptime: number;
  version: string;
  database?: boolean;
  redis?: boolean;
}

async function healthCheck(): Promise<HealthStatus> {
  const startTime = Date.now();
  let dbHealthy = true;
  let redisHealthy = true;

  
  // Check database connection
  try {
    // Add your database health check here
    // Example: await db.select().from(health).limit(1);
  } catch (error) {
    console.error('Database health check failed:', error);
    dbHealthy = false;
  }
  

  
  // Check Redis connection (if using Redis for sessions/cache)
  try {
    // Add your Redis health check here
    // Example: await redis.ping();
  } catch (error) {
    console.error('Redis health check failed:', error);
    redisHealthy = false;
  }
  

  const responseTime = Date.now() - startTime;
  const isHealthy = dbHealthy && redisHealthy && responseTime < 5000;

  return {
    status: isHealthy ? 'healthy' : 'unhealthy',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    version: process.env.npm_package_version || '1.0.0',
    database: dbHealthy,
    redis: redisHealthy,
  };
}

// HTTP health endpoint
const server = Bun.serve({
  port: process.env.HEALTH_CHECK_PORT || 8080,
  async fetch(req) {
    if (new URL(req.url).pathname === '/health') {
      const health = await healthCheck();
      return Response.json(health, {
        status: health.status === 'healthy' ? 200 : 503
      });
    }
    return new Response('Not Found', { status: 404 });
  }
});

console.log(`Health check server running on port ${server.port}`);
