-- Database initialization script
-- Generated by create-karetech-stack

CREATE DATABASE IF NOT EXISTS saas-preset-test;

-- Create user if not exists (PostgreSQL syntax)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'saas-preset-test_user') THEN
        CREATE ROLE saas-preset-test_user WITH LOGIN PASSWORD 'development_password';
    END IF;
END
$$;

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE saas-preset-test TO saas-preset-test_user;

-- Health check table
CREATE TABLE IF NOT EXISTS health (
    id SERIAL PRIMARY KEY,
    status VARCHAR(10) DEFAULT 'ok',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO health (status) VALUES ('ok') ON CONFLICT DO NOTHING;
