#!/usr/bin/env bun
/**
 * Claude Code Post-commit Hook for minimal-preset-test
 * Updates Beads tracking after successful commits
 * Generated by create-karetech-stack
 */


// Beads integration not enabled for this project
console.log('ℹ️  Post-commit hook ready (Beads not configured)');

