import { test, expect } from '@playwright/test';

/**
 * Example E2E tests
 * Generated by create-karetech-stack
 */

test.describe('Homepage', () => {
  test('should load successfully', async ({ page }) => {
    await page.goto('/');

    await expect(page).toHaveTitle(/saas-preset-test/i);
    await expect(page.getByRole('main')).toBeVisible();
  });

  test('should have working navigation', async ({ page }) => {
    await page.goto('/');

    // Test navigation elements are present
    const nav = page.getByRole('navigation');
    await expect(nav).toBeVisible();
  });

  
  test('should handle authentication flow', async ({ page }) => {
    await page.goto('/');

    // Test login button is present
    const loginButton = page.getByTestId('login-button');
    if (await loginButton.isVisible()) {
      await expect(loginButton).toBeVisible();
    }
  });
  
});

test.describe('Responsiveness', () => {
  test('should work on mobile viewport', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/');

    await expect(page.getByRole('main')).toBeVisible();
  });

  test('should work on tablet viewport', async ({ page }) => {
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.goto('/');

    await expect(page.getByRole('main')).toBeVisible();
  });

  test('should work on desktop viewport', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');

    await expect(page.getByRole('main')).toBeVisible();
  });
});
